name: tina
channels:
  - nvidia/label/cuda-11.8.0
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - binutils_impl_linux-64=2.40=h5293946_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - cuda=11.8.0=0
  - cuda-cccl=11.8.89=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=11.8.0=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=11.8.86=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=11.8.86=0
  - cuda-demo-suite=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-driver-dev=11.8.89=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.8.89=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.8.86=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.8.86=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=11.8.87=0
  - cuda-profiler-api=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-visual-tools=11.8.0=0
  - gcc=14.2.0=h96c4ede_2
  - gcc_impl_linux-64=14.2.0=hdb7739f_2
  - gds-tools=1.4.0.31=0
  - gxx=14.2.0=h96c4ede_2
  - gxx_impl_linux-64=14.2.0=h2ead766_2
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=14.2.0=h9c4974d_102
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libsanitizer=14.2.0=hed042b8_2
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-devel_linux-64=14.2.0=h9c4974d_102
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - nsight-compute=2022.3.0.22=0
  - openssl=3.0.16=h5eee18b_0
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.5.2
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiohttp-cors==0.8.0
      - aiosignal==1.3.2
      - airportsdata==20250224
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.13.2
      - anyio==4.9.0
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bitsandbytes==0.45.3
      - blake3==1.0.4
      - blinker==1.9.0
      - blobfile==3.0.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorful==0.5.6
      - compressed-tensors==0.9.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==3.4.1
      - deepspeed==0.16.4
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.8.1
      - exceptiongroup==1.2.2
      - fastapi==0.115.12
      - filelock==3.18.0
      - fire==0.7.0
      - flash-attn==2.7.3
      - flask==3.1.0
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gguf==0.10.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.24.2
      - google-auth==2.38.0
      - googleapis-common-protos==1.69.2
      - grpcio==1.71.0
      - h11==0.14.0
      - hf-xet==1.1.10
      - hjson==3.1.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.35.0
      - idna==3.10
      - importlib-metadata==8.6.1
      - interegular==0.3.3
      - itsdangerous==2.2.0
      - jaxtyping==0.3.0
      - jinja2==3.1.4
      - jiter==0.9.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kaleido==0.2.1
      - kiwisolver==1.4.8
      - lark==1.2.2
      - latex2sympy2-extended==1.0.6
      - lm-format-enforcer==0.10.11
      - lxml==5.3.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - math-verify==0.5.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mistral-common==1.5.4
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.2.0
      - multiprocess==0.70.16
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.11.1.4
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - nvitop==1.4.2
      - openai==1.68.2
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.37.0
      - opentelemetry-exporter-prometheus==0.58b0
      - opentelemetry-proto==1.37.0
      - opentelemetry-sdk==1.37.0
      - opentelemetry-semantic-conventions==0.58b0
      - orjson==3.10.16
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==24.2
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post5
      - peft==0.15.0
      - pillow==11.0.0
      - pip==25.0.1
      - platformdirs==4.3.7
      - plotly==5.0.0rc2
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.0
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - py-spy==0.4.0
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycountry==24.6.1
      - pycryptodomex==3.22.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-extra-types==2.10.5
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.3.0
      - ray==2.44.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.23.1
      - rsa==4.9
      - safetensors==0.5.3
      - schedulefree==1.4.1
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentence-transformers==3.4.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.24.1
      - setproctitle==1.3.5
      - simple-parsing==0.1.7
      - six==1.17.0
      - smart-open==7.1.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.46.1
      - sympy==1.13.1
      - tenacity==9.0.0
      - termcolor==2.5.0
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - tqdm==4.67.1
      - transformers==4.50.0
      - triton==3.1.0
      - trl==0.15.2
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - virtualenv==20.29.3
      - wadler-lindig==0.1.4
      - wandb==0.19.8
      - watchfiles==1.0.4
      - websockets==15.0.1
      - werkzeug==3.1.3
      - word2number==1.1
      - wrapt==1.17.2
      - xgrammar==0.1.16
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.21.0
