name: tina_eval
channels:
  - nvidia/label/cuda-11.8.0
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - cuda=11.8.0=0
  - cuda-cccl=11.8.89=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=11.8.0=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=11.8.86=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=11.8.86=0
  - cuda-demo-suite=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-driver-dev=11.8.89=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.8.89=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.8.86=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.8.86=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=11.8.87=0
  - cuda-profiler-api=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-visual-tools=11.8.0=0
  - expat=2.7.1=h6a678d5_0
  - gds-tools=1.4.0.31=0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - nsight-compute=2022.3.0.22=0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - aenum==3.1.15
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiohttp-cors==0.8.1
      - aiosignal==1.4.0
      - airportsdata==20250909
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.13.2
      - anyio==4.10.0
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - blake3==1.0.6
      - cachetools==5.5.2
      - certifi==2025.8.3
      - chardet==5.2.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - colorful==0.5.7
      - colorlog==6.9.0
      - compressed-tensors==0.9.1
      - dataproperty==1.1.0
      - datasets==3.4.1
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - fastapi==0.117.1
      - filelock==3.19.1
      - flash-attn==2.7.3
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - gguf==0.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.19.2
      - google-auth==2.40.3
      - googleapis-common-protos==1.65.0
      - grpcio==1.75.0
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.35.0
      - idna==3.10
      - importlib-metadata==8.4.0
      - interegular==0.3.3
      - jinja2==3.1.4
      - jiter==0.11.0
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - langcodes==3.5.0
      - language-data==1.3.0
      - lark==1.2.2
      - latex2sympy2-extended==1.0.6
      - lighteval==0.8.1
      - lm-format-enforcer==0.10.12
      - lxml==6.0.2
      - marisa-trie==1.3.1
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - mbstrdecoder==1.1.4
      - mdurl==0.1.2
      - mistral-common==1.8.5
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.13.0
      - nltk==3.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - openai==1.108.2
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.27.0
      - opentelemetry-exporter-prometheus==0.48b0
      - opentelemetry-proto==1.27.0
      - opentelemetry-sdk==1.27.0
      - opentelemetry-semantic-conventions==0.48b0
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==25.0
      - pandas==2.3.2
      - partial-json-parser==0.2.1.1.post6
      - pathvalidate==3.3.1
      - peft==0.17.1
      - pillow==11.0.0
      - platformdirs==4.4.0
      - portalocker==3.2.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==3.20.3
      - psutil==7.1.0
      - py-cpuinfo==9.0.0
      - py-spy==0.4.1
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycountry==24.6.1
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.5
      - pygments==2.19.2
      - pytablewriter==1.2.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - ray==2.49.2
      - referencing==0.36.2
      - regex==2025.9.18
      - requests==2.32.5
      - rich==14.1.0
      - rouge-score==0.1.2
      - rpds-py==0.27.1
      - rsa==4.9.1
      - sacrebleu==2.5.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.38.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.3.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.48.0
      - sympy==1.13.1
      - tabledata==1.3.4
      - tabulate==0.9.0
      - tcolorpy==0.1.7
      - termcolor==2.3.0
      - threadpoolctl==3.6.0
      - tiktoken==0.11.0
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - transformers==4.56.2
      - triton==3.1.0
      - typepy==1.3.4
      - typer==0.19.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.36.0
      - uvloop==0.21.0
      - virtualenv==20.34.0
      - wandb==0.22.0
      - watchfiles==1.1.0
      - websockets==15.0.1
      - wrapt==1.17.3
      - xgrammar==0.1.25
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0